### ISSUE TITLE
add support for compliance reports

### ISSUE THREAD

**Issue by chen-keinan** [aquasecurity/defsec#1022]
Add support for compliance reports.

introduce a compliance report embed it to be expose for Trivy use , example

```yaml
---
spec:
  id: "0001"
  title: nsa
  description: National Security Agency - Kubernetes Hardening Guidance
  relatedResources : 
    - https://www.nsa.gov/Press-Room/News-Highlights/Article/Article/2716980/nsa-cisa-release-kubernetes-hardening-guidance/
  version: "1.0"
  controls:
    - name: Non-root containers
      description: 'Check that container is not running as root'
      id: '1.0'
      checks:
        - id: AVD-KSV-0012
      severity: 'MEDIUM'
    - name: Immutable container file systems
      description: 'Check that container root file system is immutable'
  ```
