### ISSUE TITLE
yaml parsing error

### ISSUE THREAD

**Issue by afdesk** [aquasecurity/defsec#703]
Hi! we have some issue )

the customer gets an error (https://github.com/aquasecurity/trivy/issues/2362) when try to scan a helm chart with variables:
the error:
```sh
yaml: invalid map key: map[string]interface {}{"COMPONENT_NAME":interface {}(nil)}
```
`Chart.yaml`:
```yaml
apiVersion: v2
name: {{COMPONENT_NAME}}
version: {{COMPONENT_VERSION}}
description: A Helm chart for Kubernetes
keywords:
- kublr
- audit
```
The problem appears here:
https://github.com/aquasecurity/defsec/blob/0c2778fa5a4f6afb598f25807d597cc16f7af0ac/pkg/scanners/helm/parser/parser.go#L136-L139

Could you look into it? thanks a lot!
